language: python
python:
  - '2.7'
  - '3.5'

# https://docs.travis-ci.com/user/docker/
sudo: required

services:
  - docker

env:
  global:
    - PUBSUB_EMULATOR_HOST=127.0.0.1:8538

before_install:
  - docker pull bigtruedata/gcloud-pubsub-emulator
  - docker run -d --name emulator --rm -p 8538:8538 bigtruedata/gcloud-pubsub-emulator start --host-port=0.0.0.0:8538 --data-dir=/data

install:
  - pip install -r requirements.txt

script:
  - echo $PUBSUB_EMULATOR_HOST

after_script:
  - docker rm -f emulator
